# Generated by Django 3.1.4 on 2021-03-05 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0001_initial'),
        ('products', '0001_initial'),
        ('institutions', '0001_initial'),
        ('categories', '0002_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('name', models.CharField(max_length=255)),
                ('units', models.DecimalField(decimal_places=12, max_digits=27)),
                ('data', models.JSONField()),
                ('value', models.DecimalField(blank=True, decimal_places=12, max_digits=27)),
                ('current_eval', models.BigIntegerField(blank=True)),
                ('ytd_eval', models.IntegerField(blank=True, null=True)),
                ('avg_eval', models.IntegerField(blank=True, null=True)),
                ('total_eval', models.IntegerField(blank=True, null=True)),
                ('weight_eval', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='categories.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='currencies.currency')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='institutions.institution')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='products.product')),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.portfolio',),
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.portfolio',),
        ),
    ]
