# Generated by Django 3.1.4 on 2021-03-11 10:46

from django.db import migrations, models


def change_values(apps, schema):
    Portfolio = apps.get_model('portfolio.Portfolio')
    for p in Portfolio.objects.all():
        eval = p.data.get('evaluation', None) if p.data else None
        if eval:
            p.data['evaluation'] = eval / 10000
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='avg_eval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='current_eval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='total_eval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='weight_eval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='ytd_eval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(change_values)
    ]
