baker.make(Institution, name="Česká spořitelna", categories=[Category.get_bank_account(), Category.get_bond()], active=True)
baker.make(Institution, name="Komerční banka", categories=[Category.get_bank_account(), Category.get_bond()], active=True)
baker.make(Institution, name="ČSOB banka", categories=[Category.get_bank_account(), Category.get_bond()], active=True)
baker.make(Institution, name="Air bank", categories=[Category.get_bank_account()], active=True)
baker.make(Institution, name="Equa banka", categories=[Category.get_bank_account()], active=True)
baker.make(Institution, name="mBank", categories=[Category.get_bank_account()], active=True)
baker.make(Institution, name="Unicredit", categories=[Category.get_bank_account()], active=True)
baker.make(Institution, name="Sberbank", categories=[Category.get_bank_account()], active=True)
baker.make(Institution, name="Moneta money bank", categories=[Category.get_bank_account()], active=True)
baker.make(Institution, name="FIO banka", categories=[Category.get_bank_account(), Category.get_bond()], active=True)
baker.make(Institution, name="JT banka", categories=[Category.get_bank_account(), Category.get_bond()], active=True)
baker.make(Institution, name="Raiffeisenbank", categories=[Category.get_bank_account()], active=True)

baker.make(Product, name="Běžný účet", active=True, currencies=[Currency.get_czk()], institutions=Institution.objects.all(), category=Category.get_bank_account())
baker.make(Product, name="Podnikatelský účet", active=True, currencies=[Currency.get_czk(), Currency.get_eur()], institutions=Institution.objects.filter(id__in=[1,2,3,4,5]), category=Category.get_bank_account())
baker.make(Product, name="České státní dluhopisy", active=True, currencies=[Currency.get_czk()], institutions=Institution.objects.filter(id__in=[10,11]), category=Category.get_bond())
baker.make(Product, name="US bonds", active=True, currencies=[Currency.get_usd()], institutions=Institution.objects.all(), category=Category.get_bond())