# Generated by Django 3.1.4 on 2021-03-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=12, max_digits=27)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_values', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'hodnota portfolia',
                'verbose_name_plural': 'hodnoty portfolia',
                'unique_together': {('portfolio', 'date')},
            },
        ),
    ]
