# Generated by Django 3.1.4 on 2021-03-05 13:23

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('categories', '0002_category_order'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('evaluation', models.PositiveBigIntegerField()),
                ('value', models.DecimalField(decimal_places=12, max_digits=27)),
                ('data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
                ('currencies', models.ManyToManyField(blank=True, related_name='_product_currencies_+', to='currencies.Currency')),
                ('institutions', models.ManyToManyField(blank=True, related_name='products', to='institutions.Institution')),
            ],
            options={
                'verbose_name': 'produkt',
                'verbose_name_plural': 'produkty',
            },
        ),
    ]
