# Generated by Django 3.1.4 on 2021-03-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='evaluation',
            field=models.BigIntegerField(),
        ),
    ]
