# Generated by Django 3.1.4 on 2021-03-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210311_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('order', 'name'), 'verbose_name': 'produkt', 'verbose_name_plural': 'produkty'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveBigIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
