PAYMENT_FREQUENCY_MONTH = 'MONTH'
PAYMENT_FREQUENCY_QUARTER = 'QUARTER'
PAYMENT_FREQUENCY_HALF = 'HALF'
PAYMENT_FREQUENCY_YEARLY = 'YEAR'

BOND_PAYMENT_FREQUENCY_CHOICES = (
    (PAYMENT_FREQUENCY_YEARLY, 'ročně'),
    (PAYMENT_FREQUENCY_HALF, 'půlročně'),
    (PAYMENT_FREQUENCY_QUARTER, 'čtvrtletně'),
    (PAYMENT_FREQUENCY_MONTH, 'měsíčně'),
)


SAVING_ACCOUNT_PAYMENT_FREQUENCY_CHOICES = (
    (PAYMENT_FREQUENCY_YEARLY, 'ročně'),
    (PAYMENT_FREQUENCY_HALF, 'půlročně'),
    (PAYMENT_FREQUENCY_QUARTER, 'čtvrtletně'),
    (PAYMENT_FREQUENCY_MONTH, 'měsíčně'),
)

BUILDING_SAVING_PAYMENT_FREQUENCY_CHOICES = (
    (PAYMENT_FREQUENCY_YEARLY, 'ročně'),
    (PAYMENT_FREQUENCY_MONTH, 'měsíčně'),
)


PENSION_SAVING_FORM_OLD = 'OLD'
PENSION_SAVING_FORM_NEW = 'NEW'
PENSION_SAVING_FORM_CHOICES = (
    (PENSION_SAVING_FORM_OLD, 'OLD'),
    (PENSION_SAVING_FORM_NEW, 'NEW'),
)


STRATEGY_GUARANTEED = 'GUARANTEED'
STRATEGY_CONSERVATIVE = 'CONSERVATIVE'
STRATEGY_BALANCED = 'BALANCED'
STRATEGY_DYNAMIC = 'DYNAMIC'

PENSION_SAVING_STRATEGY_CHOICES = (
    (STRATEGY_GUARANTEED, 'GUARANTEED'),
    (STRATEGY_CONSERVATIVE, 'CONSERVATIVE'),
    (STRATEGY_BALANCED, 'BALANCED'),
    (STRATEGY_DYNAMIC, 'DYNAMIC'),
)

SHARE_ETF_STRATEGY_CHOICES = (
    (STRATEGY_CONSERVATIVE, 'CONSERVATIVE'),
    (STRATEGY_BALANCED, 'BALANCED'),
    (STRATEGY_DYNAMIC, 'DYNAMIC'),
)
